### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [Siddharth11/Colorful#19]
Hi, there are a few broken links:

- [ ] http://jxnblk.com/colorable/ (file: README.md, status code: 404)
- [ ] http://www.pictaculous.com/ (file: README.md, error: ENOTFOUND)
- [ ] http://jxnblk.com/shade/ (file: README.md, status code: 404)
- [ ] http://www.checkmycolours.com/ (file: README.md, error: ENOTFOUND)
- [ ] http://www.dasplankton.de/ContrastA/ (file: README.md, status code: 500)
- [ ] http://colorsupplyyy.com/app/ (file: README.md, error: EAI_AGAIN)
- [ ] http://www.colourlovers.com/ (file: README.md, error: ECONNRESET)
- [ ] http://www.lolcolors.com/palettes/popular (file: README.md, status code: 404)
- [ ] http://color.farm/ (file: README.md, error: ECONNRESET)
- [ ] https://blog.graphiq.com/finding-the-right-color-palettes-for-data-visualizations-fcd4e707a283#.k1zjxtfet (file: README.md, error: ENOTFOUND)
- [ ] https://medium.com/life-tips/the-unfinished-basics-of-colour-292858f62e62#.b1z1ejmsg (file: README.md, status code: 410)
- [ ] https://medium.com/@usabilla/how-to-design-for-color-blindness-62d4d8ae9f6a#.uujosqblu (file: README.md, status code: 410)
- [ ] https://journal.helabs.com/oiling-the-color-wheel-with-jade-sass-5688ceada87c#.frc7e0rj5 (file: README.md, error: ENOTFOUND)
- [ ] http://www.tigercolor.com/color-lab/color-theory/color-theory-intro.htm (file: README.md, error: ENOTFOUND)
- [ ] http://www.ifweassume.com/2013/05/cubehelix-or-how-i-learned-to-love.html (file: README.md, status code: 404)

**Comment by Siddharth11** [comment]
Hi @ndsvw, thanks for pointing this out! 

Do you want to raise a PR to fix these links?
